export default class Currency {
  public static availableCurrency = {
    AED: 'Uni Emirat Arab',
    AFN: 'Afghanistan',
    ALL: 'Albania',
    AMD: 'Armenia',
    ANG: 'Antillen Belanda',
    AOA: 'Angola',
    ARS: 'Argentina',
    AUD: 'Australia',
    AWG: 'Aruba',
    AZN: 'Azerbaijan',
    BAM: 'Bosnia dan Herzegovina',
    BBD: 'Barbados',
    BDT: 'Bangladesh',
    BGN: 'Bulgaria',
    BHD: 'Bahrain',
    BIF: 'Burundi',
    BMD: 'Bermuda',
    BND: 'Brunei',
    BOB: 'Bolivia',
    BRL: 'Brasil',
    BSD: 'Bahamas',
    BTC: 'Bitcoin',
    BTN: 'Bhutan',
    BWP: 'Botswana',
    BYN: 'Belarus',
    BZD: 'Belize',
    CAD: 'Kanada',
    CDF: 'Kongo',
    CHF: 'Swiss',
    CLF: 'Chile',
    CLP: 'Chile',
    CNH: 'Yuan Tiongkok (Offshore)',
    CNY: 'Tiongkok',
    COP: 'Kolombia',
    CRC: 'Kosta Rika',
    CUC: 'Peso Kuba',
    CUP: 'Peso Kuba',
    CVE: 'Cape Verde',
    CZK: 'Ceko',
    DJF: 'Djibouti',
    DKK: 'Denmark',
    DOP: 'Dominika',
    DZD: 'Aljazair',
    EGP: 'Mesir',
    ERN: 'Eritrea',
    ETB: 'Ethiopia',
    EUR: 'Euro',
    FJD: 'Fiji',
    FKP: 'Kepulauan Falkland',
    GBP: 'Inggris',
    GEL: 'Georgia',
    GGP: 'Guernsey',
    GHS: 'Ghana',
    GIP: 'Gibraltar',
    GMD: 'Gambia',
    GNF: 'Guinea',
    GTQ: 'Guatemala',
    GYD: 'Guyana',
    HKD: 'Hong Kong',
    HNL: 'Honduras',
    HRK: 'Kroasia',
    HTG: 'Haiti',
    HUF: 'Hungary',
    IDR: 'Indonesia',
    ILS: 'Israel',
    IMP: 'Pound Isle of Man',
    INR: 'India',
    IQD: 'Irak',
    IRR: 'Iran',
    ISK: 'Iceland',
    JEP: 'Jersey',
    JMD: 'Jamaika',
    JOD: 'Yordania',
    JPY: 'Jepang',
    KES: 'Kenya',
    KGS: 'Kyrgyzstan',
    KHR: 'Kamboja',
    KMF: 'Comoros',
    KPW: 'Won Korea Utara',
    KRW: 'Korea Selatan',
    KWD: 'Kuwait',
    KYD: 'Kepulauan Cayman',
    KZT: 'Kazakhstan',
    LAK: 'Laos',
    LBP: 'Lebanon',
    LKR: 'Sri Lanka',
    LRD: 'Liberia',
    LSL: 'Lesotho',
    LYD: 'Libya',
    MAD: 'Morocco',
    MDL: 'Moldova',
    MGA: 'Madagaskar',
    MKD: 'Macedonia Utara',
    MMK: 'Myanmar',
    MNT: 'Mongolia',
    MOP: 'Makau',
    MRU: 'Mauritania',
    MUR: 'Mauritius',
    MVR: 'Maldives',
    MWK: 'Malawi',
    MXN: 'Meksiko',
    MYR: 'Malaysia',
    MZN: 'Mozambique',
    NAD: 'Namibia',
    NGN: 'Nigeria',
    NIO: 'Nicaragua',
    NOK: 'Norwegia',
    NPR: 'Nepal',
    NZD: 'Selandia Baru',
    OMR: 'Oman',
    PAB: 'Panama',
    PEN: 'Peru',
    PGK: 'Papua Nugini',
    PHP: 'Filipina',
    PKR: 'Pakistan',
    PLN: 'Polandia',
    PYG: 'Paraguay',
    QAR: 'Qatar',
    RON: 'Rumania',
    RSD: 'Serbia',
    RUB: 'Rusia',
    RWF: 'Rwanda',
    SAR: 'Arab Saudi',
    SBD: 'Kepulauan Solomon',
    SCR: 'Seychelles',
    SDG: 'Sudan',
    SEK: 'Swedia',
    SGD: 'Singapura',
    SHP: 'Saint Helena',
    SLL: 'Sierra Leone',
    SOS: 'Somalia',
    SRD: 'Suriname',
    SSP: 'Sudan Selatan',
    STD: 'São Tomé dan Príncipe Dobra',
    STN: 'São Tomé dan Príncipe Dobra',
    SVC: 'El Salvador',
    SYP: 'Suriah',
    SZL: 'Eswatini',
    THB: 'Thailand',
    TJS: 'Tajikistan',
    TMT: 'Turkmenistan',
    TND: 'Tunisia',
    TOP: 'Tonga',
    TRY: 'Turki',
    TTD: 'Trinidad dan Tobago',
    TWD: 'Taiwan Baru',
    TZS: 'Tanzania',
    UAH: 'Ukraina',
    UGX: 'Uganda',
    USD: 'Amerika Serikat',
    UYU: 'Uruguay',
    UZS: 'Uzbekistan',
    VES: 'Venezuela',
    VND: 'Vietnam',
    VUV: 'Vanuatu',
    WST: 'Samoa',
    XAF: 'Franc CFA Afrika Tengah',
    XAG: 'Silver Ounce',
    XAU: 'Gold Ounce',
    XCD: 'Dolar Karibia Timur',
    XDR: 'Hak Menggambar Khusus',
    XOF: 'Franc CFA Afrika Barat',
    XPD: 'Palladium Ounce',
    XPF: 'Franc CFP',
    XPT: 'Platinum Ounce',
    YER: 'Yaman',
    ZAR: 'Afrika Selatan',
    ZMW: 'Zambia',
    ZWL: 'Dolar Zimbabwe',
  };
}
